version: "3.8"

services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - JWT_SECRET_KEY=e3562575bcbb2a7966bd11de99344452824591b0ec96c4ea97ec47509101d5dd
    